name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Nuget
      run: NuGet/setup-nuget@v1.0.2
    - name: Restore Packages
    - run: nuget restore GildedRose.sln
    
